# Анализ поведения пользователей приложения "Ненужные вещи"

Автор: Александр Лагутин.

Начат: 6 января 2023 г в 19:00.
Завершён: 0 месяца 2022 г в 00:00.

Время подготовки: 8 рабочих часов (1 рабочий день).

Декомпозиция задачи - под заголовком 1.4.

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Описание-проекта" data-toc-modified-id="Описание-проекта-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Описание проекта</a></span><ul class="toc-item"><li><span><a href="#Заказчик" data-toc-modified-id="Заказчик-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Заказчик</a></span></li><li><span><a href="#Вопросы-заказчика" data-toc-modified-id="Вопросы-заказчика-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Вопросы заказчика</a></span></li><li><span><a href="#Входные-данные" data-toc-modified-id="Входные-данные-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Входные данные</a></span><ul class="toc-item"><li><span><a href="#Термины" data-toc-modified-id="Термины-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Термины</a></span></li><li><span><a href="#Описание-данных" data-toc-modified-id="Описание-данных-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>Описание данных</a></span><ul class="toc-item"><li><span><a href="#Источники-установок-mobile_sources.csv" data-toc-modified-id="Источники-установок-mobile_sources.csv-1.3.2.1"><span class="toc-item-num">1.3.2.1&nbsp;&nbsp;</span>Источники установок <code>mobile_sources.csv</code></a></span></li><li><span><a href="#События-mobile_dataset.csv" data-toc-modified-id="События-mobile_dataset.csv-1.3.2.2"><span class="toc-item-num">1.3.2.2&nbsp;&nbsp;</span>События <code>mobile_dataset.csv</code></a></span></li></ul></li></ul></li><li><span><a href="#План-работы-(&quot;декомпозиция&quot;)" data-toc-modified-id="План-работы-(&quot;декомпозиция&quot;)-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>План работы ("декомпозиция")</a></span></li><li><span><a href="#Инструменты" data-toc-modified-id="Инструменты-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Инструменты</a></span><ul class="toc-item"><li><span><a href="#Импорт-библиотек" data-toc-modified-id="Импорт-библиотек-1.5.1"><span class="toc-item-num">1.5.1&nbsp;&nbsp;</span>Импорт библиотек</a></span></li><li><span><a href="#Определения-констант" data-toc-modified-id="Определения-констант-1.5.2"><span class="toc-item-num">1.5.2&nbsp;&nbsp;</span>Определения констант</a></span></li><li><span><a href="#Определения-функций" data-toc-modified-id="Определения-функций-1.5.3"><span class="toc-item-num">1.5.3&nbsp;&nbsp;</span>Определения функций</a></span><ul class="toc-item"><li><span><a href="#Загрузка-и-обзор-данных" data-toc-modified-id="Загрузка-и-обзор-данных-1.5.3.1"><span class="toc-item-num">1.5.3.1&nbsp;&nbsp;</span>Загрузка и обзор данных</a></span></li><li><span><a href="#Исправление-данных" data-toc-modified-id="Исправление-данных-1.5.3.2"><span class="toc-item-num">1.5.3.2&nbsp;&nbsp;</span>Исправление данных</a></span></li><li><span><a href="#Отображение-данных" data-toc-modified-id="Отображение-данных-1.5.3.3"><span class="toc-item-num">1.5.3.3&nbsp;&nbsp;</span>Отображение данных</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Обзор-и-исправление-данных" data-toc-modified-id="Обзор-и-исправление-данных-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Обзор и исправление данных</a></span><ul class="toc-item"><li><span><a href="#Итоги-обзора-и-исправления-данных" data-toc-modified-id="Итоги-обзора-и-исправления-данных-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Итоги обзора и исправления данных</a></span></li></ul></li><li><span><a href="#Исследовательский-анализ-данных" data-toc-modified-id="Исследовательский-анализ-данных-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Исследовательский анализ данных</a></span><ul class="toc-item"><li><span><a href="#Итоги-подготовки-информации-о-расходах:" data-toc-modified-id="Итоги-подготовки-информации-о-расходах:-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Итоги подготовки информации о расходах:</a></span></li></ul></li><li><span><a href="#Гипотезы-и-проверки" data-toc-modified-id="Гипотезы-и-проверки-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Гипотезы и проверки</a></span><ul class="toc-item"><li><span><a href="#Итоги-проверки-гипотез" data-toc-modified-id="Итоги-проверки-гипотез-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Итоги проверки гипотез</a></span></li></ul></li><li><span><a href="#Общие-итоги" data-toc-modified-id="Общие-итоги-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Общие итоги</a></span></li></ul></div>

## Описание проекта

### Заказчик

Заказчик: продакт-менеджер мобильного приложения "Ненужные вещи".

Описание продукта: мобильное приложение, в котором пользователи могут:
- выставить объявление с описанием вещи, которую хотят отдать:
  - в том числе добавить фотографии;
- подыскать себе вещь с помощью рекомендаций, поиска по тексту, а также "карты ближайших вещей";
- добавить вещь в избранное;
- получить контакт (номер телефона) владельца выбранной вещи;
- связаться с владельцем по голосовой связи внутри приложения.

### Вопросы заказчика

- Какие действия увеличивают конверсию пользователя в целевое действие?
- Какие сценарии использования приложения выделяются?
- Как различается время между распространёнными событиями?

**Для чего**: чтобы увеличить вовлечённость пользователей в приложение.

Заказчик желает разделить ("сегментировать") пользователей на группы по их типичным действиям, чтобы далее к каждой группе применять подходящие для её вовлечения меры.

Он желает определять по наступившим у пользователя событиям понять, придёт ли пользователь к целевому событию. И определить, какое событие может подтолкнуть этого пользователя к целевому.

Также заказчик ищет предложения, как можно улучшить приложение. Поведение пользователей может дать подсказки.

### Входные данные

Логи сервиса за первый месяц:
- Лог источников установок приложения
- Лог событий внутри приложения

#### Термины

Специальные термины не упомянуты.

#### Описание данных

##### Источники установок `mobile_sources.csv`

- `userId` - идентификатор пользователя;
- `source` - источник, с которого пользователь установил приложение.

##### События `mobile_dataset.csv`

- `event.time` - момент события;
- `user.id` - идентификатор пользователя.
- `event.name` - действие пользователя.

Виды действий:

- `tips_show` — увидел рекомендованные объявления,
- `tips_click` — кликнул по рекомендованному объявлению,
- `search_1`—`search_7` — разные действия, связанные с поиском по сайту,
- `map` — открыл карту объявлений,
- `advert_open` — открыл карточки объявления,
- `photos_show` — просмотрел фотографий в объявлении,
- `favorites_add` — добавил объявление в избранное,
- `contacts_show` и `show_contacts` — посмотрел номер телефона,
- `contacts_call` — позвонил по номеру из объявления.

### План работы ("декомпозиция")

- [ ] Подготовить данные:
  - [ ] привести к норме названия столбцов;
  - [ ] привести данные к подходящим типам;
  - [ ] привести к единому виду названия событий:
    - [ ] `show_contacts` в `contacts_show`
  - [ ] обработать пропуски:
    - [ ] выбрать, чем заполнить (или оставить) и почему;
    - [ ] заполнить, если требуется;
    - [ ] описать причины, которые могли привести к пропускам;
  - [ ] проверить повторы, в том числе повторы установок с одинаковым `user_id`:
    - [ ] что могло их вызвать?
    - [ ] убрать или оставить?
    - [ ] что можно порекомендовать?
  - [ ] дополнить события:
    - [ ] источник установки приложения `source`(мердж установок в события),
    - [ ] уникальным номером сессии `session_id` (по таймауту между последовательными событиями конкретных пользователей),
    - [ ] дата начала сессии `session_date`,
    - [ ] достиг ли пользователь целевого действия в данную сессию `session_reached_goal`,
    - [ ] достиг ли пользователь целевого действия хоть раз за выборку `user_reached_goal`.
- [ ] Исследовательский анализ данных:
  - [ ] Узнать, есть ли различие между множествами пользователей, которые установили приложение, и которые производили действия в нём?
  - [ ] Из каких источников установок больше?
  - [ ] Как много было действий каждого вида? История по датам.
  - [ ] Как много пользователей их совершало? История по датам (DAU).
  - [ ] Как много времени пользователи проводят в приложении? Сумма сессий за месяц, и по дням.
  - [ ] Распределения промежутков времени между распространёнными событиями.
    - [ ] Выбрать пару или несколько пар популярных событий. Почему именно эти события полезны для целей исследования?
    - [ ] Получить типичное время между ними для тех, кто совершал целевое событие, и кто не совершал.
- [ ] Анализ влияния событий на совершение целевого события;
  - [ ] Какие действия совершаются непосредтвенно перед целевым?
  - [ ] Выявить основные несколько сценариев поведения пользователей (самые частые последовательности действий внутри сессий)
    - [ ] Для каждой сессии - построить порядок первых наступлений событий (например, упорядоченный список названий событий)
    - [ ] Группировать по полученным последовательностям, выбрать наиболее частые последовательности
    - [ ] Для них построить воронки конверсии уникальных пользователей в целевое действие.
- [ ] Статистическая проверка гипотез:
  - [ ] конверсия в просмотры контактов различается у двух групп: тех кто совершил `tips_show` и `tips_click`, и тех, кто совершил только `tips_show`;
  - [ ] конверсия в просмотры контактов различна у двух групп: тех кто только открывал описание предмета `advert_open`, и тех кто смотрел описание `advert_open` и просматривал фото `photos_show`.
- [ ] Описать общий вывод:
  - [ ] что исследовано (указать основные зарактеристики данных);
  - [ ] какие ответы на основные вопросы исследования;
  - [ ] какие гипотезы подтвердились или отвергнуты;
  - [ ] какие факты обнаружены;
  - [ ] какие предположения выдвинуты;
  - [ ] какие есть рекомендации:
    - [ ] кому,
    - [ ] суть рекомендации.
- [ ] Создать презентацию:
  - [ ] Описать главные вопросы
  - [ ] Описать главные ответы
  - [ ] Добавить по несколько диаграмм и величин, подкрепляющих каждый ответ.
  - [ ] Опубликовать pdf для свободного скачивания
  - [ ] Ссылку добавить в конец проектной тетради.

### Инструменты

Используем [Anaconda](https://www.anaconda.com/), окружение `ds_da_practicum_env.yml` "для Mac OS" (от 2022-03-23).

#### Импорт библиотек

In [1]:
%matplotlib inline

import datetime
import re

import pandas as pd
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
import seaborn as sns

#### Определения констант

In [2]:
# set size for all charts
FIGSIZE = (10, 5)

#### Определения функций

##### Загрузка и обзор данных

In [3]:
def load(name, ext='csv', sep=','):
    """Return pandas DataFrame by filename"""
    filename = name + '.' + ext
    try:
        df = pd.read_csv(filename)
    except FileNotFoundError:
        df = pd.read_csv(
            'https://code.s3.yandex.net/datasets/' + filename, sep=sep
        )
    correct_column_names(df)
    overview(df)
    return df

In [4]:
def overview(data):
    """Display an overview of the data to detect common data problems"""
    display(data.sample(5))
    dupes = data.duplicated().sum()
    dupes_rate = dupes / len(data)
    print(f'Полностью совпадающих строк: {dupes} ({dupes_rate:.2%})\n')
    data.info()
    display(count_nans(data))
    print(get_filled_rows_share(data))

In [5]:
def count_nans(data):
    """Return a pandas DataFrame with the number of missing values"""
    nans = []
    for column in data.columns:
        # count the number of missing values
        missing = data[column].isna().sum()
        # calculate the share of missing values
        part = round(missing * 100 / len(data), 2)
        # count the number of distinct values
        uniques = data[column].sort_values().nunique()
        nans.append([column, missing, part, uniques])

    return (
        pd.DataFrame(
            data=nans, columns=['column', 'na_count', 'na_%', 'unique_count']
        )
        .sort_values(['na_count', 'unique_count'], ascending=False)
        .set_index('column')
    )

In [6]:
def get_filled_rows_share(df):
    """Return a string containing number of rows with no missing values"""
    share = 1 - df.isna().any(axis=1).sum() / len(df)
    return f'Заполненных строк без пропусков: {share:.02%}'

##### Исправление данных

In [7]:
def correct_column_names(df):
    """Convert column names to valid snake_case in place"""
    df.columns = df.columns.str.strip()
    df.columns = list(map(to_snake_case, df.columns))


def to_snake_case(name):
    """Return name converted to valid snake_case"""
    name = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    name = re.sub('__([A-Z])', r'_\1', name)
    name = re.sub('([a-z0-9])([A-Z])', r'\1_\2', name)
    name = re.sub('\.', '_', name)
    return name.lower()

In [8]:
def fillnaby(df, column, groupby, func='median'):
    """Fill in missing values with group-aggregated values in-place"""
    df[column] = df[column].fillna(df.groupby(groupby)[column].transform(func))

In [9]:
# эта ячейка содержит заготовку для функции
# из проектов ячейку надо удалять
# TODO: функция, которая будет обнаруживать ячейки
# с датами и временем в виде строки, и преобразовывать
# эти строки в соответствующий тип
# pd.to_datetime(value)

date_pattern = (
    '^(?:\\d{4})-(?:\\d{2})-(?:\\d{2})'  # date
    '[ T](?:\\d{2}):(?:\\d{2}):(?:\\d{2}(?:\\.\\d*)?)'  # time
    '(?:(?:-(?:\\d{2}):(?:\\d{2})|Z)?)$'  # timezone
)

# для проверки:
# print(re.match(date_pattern, '2021-11-04 11:11:11') is not None)
# visits['session_start'] = pd.to_datetime(visits['session_start'])
# visits['session_end'] = pd.to_datetime(visits['session_start'])

##### Отображение данных

In [10]:
def headline(line, width=79):
    """Return the string in plain uppercase text with pseudographics"""
    return f'\n{line.upper():=^{width}}'

In [11]:
# можно было бы рисовать `bar` в случаях, когда вариантов мало.
# однако по неясной причине `bar` не рисуется, и не вызывает ошибки,
# а вызывает лишь зацикливание при построении первого же графика


def survey_columns(df):
    for column in nans_before.index:
        print(headline(column))

        uniques = realty[column].sort_values().unique()
        if len(uniques) < 20:
            print(uniques)
        print(f'Data type: {str(realty[column].dtype):>10}')
        print(f'Unique values: {len(uniques):6}')

        missing = realty[column].isna().sum()
        if missing:
            print(f'Not avaliable: {nans_before.loc[column, "na_part"]:.02%}')
        else:
            print('All values is avaliable.')

        try:
            realty.plot(
                kind='hist',
                y=column,
                bins=50,
            )
            plt.show()
        except Exception as e:
            print(str(e).capitalize())

In [12]:
# формирует и выводит график, подстроенный под наши нужды
def histf(
    data,
    column,
    show=True,
    bins=100,
    qtl=1,
    start=None,
    stop=None,
    figsize=FIGSIZE,
    **kwargs,
):
    fixed = {
        'y': column,
        'kind': 'hist',
        'bins': min(bins, len(data[column].unique())),
        'figsize': figsize,
        'title': column,
        'legend': False,
        'ec': 'black',
    }
    if 'range' not in kwargs.keys():
        if not start:
            start = data[column].min()
        if not stop:
            stop = data[column].quantile(qtl)
        kwargs['range'] = (start, stop)
    data.plot(**fixed, **kwargs)
    if show:
        plt.show()


def histf2(data, column1, column2, **kwargs):
    histf(column1, data=data, show=False, **kwargs)
    histf(column2, data=data, show=False, **kwargs)
    plt.show()


# два графика: все случаи, и те, что менее указанного квантиля
def dhistf(column, data, qtl=0.975, figsize=FIGSIZE, **kwargs):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=figsize)
    fig.suptitle('This is a somewhat long figure title', fontsize=16)

    ax1.set_title('full_data')
    ax2.set_title(f'{qtl:.2%} quantile')
    histf(column, data=data, ax=ax1, subplots=True, show=False, **kwargs)
    histf(
        column, data=data, ax=ax2, subplots=True, show=False, qtl=qtl, **kwargs
    )
    plt.show()


# Развитая форма этого чудовища должна принимать список квантилей,
# и строить столько графиков, сколько квантилей указано,
# и качестве центра диапазона выбирать медиану.
# Пора перейти к аналитике.

In [13]:
def typical(data, column, ratio=1.5):
    q1 = data[column].quantile(0.25)
    q3 = data[column].quantile(0.75)
    iqr = q3 - q1
    whiskers = iqr * ratio
    low = q1 - whiskers
    high = q3 + whiskers

    print(
        f'{column.title()}: min = {data[column].min()},'
        f' max = {data[column].max()},'
        f' normal range = [{low:.2f} ... {high:.2f}]'
    )

    return data.query(f'@low <= {column} <= @high')

In [14]:
def find_cat_and_num_cols(df):
    # find categorical and numerical columns

    categorical_columns = [
        c for c in df.columns if df[c].dtype.name == 'object'
    ]
    numerical_columns = [c for c in df.columns if df[c].dtype.name != 'object']

    return categorical_columns, numerical_columns


categorical_properties, quantitative_properties = find_cat_and_num_cols(
    pd.DataFrame(data=[])
)

key_column = ''


def batch_corr(data, column=key_column):
    print(headline('Коэффициенты линейной корреляции'))
    display(
        data.reindex(
            columns=(categorical_properties + quantitative_properties)
        )
        .corr()[column]
        .sort_values(ascending=False)
    )


def batch_scatter(data, column=key_column):
    for prop in quantitative_properties:
        if prop == column:
            continue
        data.plot(
            kind='scatter',
            alpha=0.2,
            figsize=FIGSIZE,
            y=column,
            x=prop,
        )
    plt.show()


def batch_box(data, column=key_column, by_props=categorical_properties):
    for prop in by_props:
        data.boxplot(
            column=column,
            by=prop,
            figsize=FIGSIZE,
        )
    plt.show()

## Обзор и исправление данных

In [15]:
load('mobile_sources')

                                   user_id  source
3606  3bb5cc38-34ad-4c52-ae47-1fa1c0185912   other
1405  2d1f649d-8333-4dbf-959b-5bd90bd6ccb0  google
1227  cb98af26-87c1-4c2b-b3a2-ad0295527144  yandex
2893  2899bb18-a262-460f-aed9-a4d8dfb56b00  google
84    236d809d-eeeb-4c49-8e94-11623f3bdb2d   other

Полностью совпадающих строк: 0 (0.00%)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4293 entries, 0 to 4292
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  4293 non-null   object
 1   source   4293 non-null   object
dtypes: object(2)
memory usage: 67.2+ KB

         na_count  na_%  unique_count
column
user_id         0   0.0          4293
source          0   0.0             3

Заполненных строк без пропусков: 100.00%

                                   user_id  source
0     020292ab-89bc-4156-9acf-68bc2783f894   other
1     cf7eda61-9349-469f-ac27-e5b6f5ec475c  yandex
2     8c356c42-3ba9-4cb6-80b8-3f868d0192c3  yandex
3     d9b06b47-0f36-419b-bbb0-3533e582a6cb   other
4     f32e1e2a-3027-4693-b793-b7b3ff274439  google
...                                    ...     ...
4288  b86fe56e-f2de-4f8a-b192-cd89a37ecd41  yandex
4289  424c0ae1-3ea3-4f1e-a814-6bac73e48ab1  yandex
4290  437a4cd4-9ba9-457f-8614-d142bc48fbeb  yandex
4291  c10055f0-0b47-477a-869e-d391b31fdf8f  yandex
4292  d157bffc-264d-4464-8220-1cc0c42f43a9  google

[4293 rows x 2 columns]

In [16]:
load('mobile_dataset')

,event_time,event_name,user_id
21792,2019-10-16 08:44:21.188329,advert_open,4328851e-3876-4bfd-9e4f-c5c348f2ba7b
1609,2019-10-07 19:27:46.607254,tips_click,7e2ecdc9-d832-467e-a6b0-be2dd4643c53
42255,2019-10-23 18:32:13.136280,photos_show,16855b4e-eefc-468c-93cb-7832f431dcd2
41840,2019-10-23 17:02:35.614000,contacts_show,ddf74fe4-d5c0-43d6-8cb6-799f4dec2b50
10728,2019-10-11 18:20:24.708420,tips_show,84edca99-f310-4f0b-a0c6-c9fc6de19382

Полностью совпадающих строк: 0 (0.00%)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74197 entries, 0 to 74196
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   event_time  74197 non-null  object
 1   event_name  74197 non-null  object
 2   user_id     74197 non-null  object
dtypes: object(3)
memory usage: 1.7+ MB

            na_count  na_%  unique_count
column
event_time         0   0.0         74197
user_id            0   0.0          4293
event_name         0   0.0            16

Заполненных строк без пропусков: 100.00%

,event_time,event_name,user_id
0,2019-10-07 00:00:00.431357,advert_open,020292ab-89bc-4156-9acf-68bc2783f894
1,2019-10-07 00:00:01.236320,tips_show,020292ab-89bc-4156-9acf-68bc2783f894
2,2019-10-07 00:00:02.245341,tips_show,cf7eda61-9349-469f-ac27-e5b6f5ec475c
3,2019-10-07 00:00:07.039334,tips_show,020292ab-89bc-4156-9acf-68bc2783f894
4,2019-10-07 00:00:56.319813,advert_open,cf7eda61-9349-469f-ac27-e5b6f5ec475c
...,...,...,...
74192,2019-11-03 23:53:29.534986,tips_show,28fccdf4-7b9e-42f5-bc73-439a265f20e9
74193,2019-11-03 23:54:00.407086,tips_show,28fccdf4-7b9e-42f5-bc73-439a265f20e9
74194,2019-11-03 23:56:57.041825,search_1,20850c8f-4135-4059-b13b-198d3ac59902
74195,2019-11-03 23:57:06.232189,tips_show,28fccdf4-7b9e-42f5-bc73-439a265f20e9
74196,2019-11-03 23:58:12.532487,tips_show,28fccdf4-7b9e-42f5-bc73-439a265f20e9

### Итоги обзора и исправления данных

- Первый;
- Второй;
- Третий.

## Исследовательский анализ данных

### Итоги подготовки информации о расходах:

- Первый;
- Второй;
- Третий.

## Гипотезы и проверки

### Итоги проверки гипотез

- Первый;
- Второй;
- Третий.

## Общие итоги

- Исследовано:
- **Подтверждённые выводы:**
- Также обнаружено, что:
- Предположения: